config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  get :search, to: 'search#result'

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  devise_for :users, controllers: {
      omniauth_callbacks: 'oauth_callbacks',
      confirmations: 'oauth_confirmations'
  }

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  concern :voteable do
    member do
      post :up
      post :down
      post :cancel
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, concerns: %i[voteable commentable] do
    resources :answers, shallow: true, concerns: %i[voteable commentable] do
      member do
        patch :best
      end
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  mount ActionCable.server => '/cable'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def result
    @params = search_params

    if @params[:q] == ''
      flash.now[:alert] = 'Search field is empty'
    else
      @result = Services::Search.call(@params)
    end
  end

  private

  def search_params
    params.permit(:q, :resource)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  RESOURCE = %w[All Question Answer Comment User]

  def result
    @resource = search_params[:resource]
    @q_text = search_params[:q]

    @q_text == '' ? flash.now[:alert] = 'Search field is empty' : return_result
  end

  private

  def search_params
    params.permit(:q, :resource)
  end

  def return_result
    @resource == 'All' ? @result = search(ThinkingSphinx) : @result = search(@resource.constantize)
  end

  def search(resource)
    resource.search @q_text
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_answer.html.slim
= link_to resource.body.truncate(50), question_path(resource.question)
em.small
  p= resource.created_at

app/views/search/_comment.html.slim
= link_to resource.body.truncate(50), question_path(resource.commentable)
em.small
  p= resource.created_at

app/views/search/_question.html.slim
= link_to resource.title, question_path(resource)
em.small
    p= resource.body.truncate(50)
    p= resource.created_at

app/views/search/_search.html.slim
.search_form
  = form_with url: search_path,
              method: :get,
              local: true,
              class: 'form-inline my-2 my-lg-0' do
    = text_field_tag(:q, '', class: 'form-control mr-sm-2')
    = select_tag(:resource,
                  options_for_select(Services::Search::RESOURCE),
                  class: 'form-control mr-sm-2')
    = submit_tag('Search', class: 'btn btn-outline-primary my-2 my-sm-0')

app/views/search/_user.html.slim
= resource.email
em.small
  p= resource.created_at

app/views/search/result.html.slim
.search_info
  - unless @params[:q] == ''
    h4= 'What: '
    = @params[:q]
    h4= 'Where: '
    = @params[:resource]
.search_result
    - if @result
      h2= "Result (#{@result.count})"
      - @result.each do |result|
        .border_secondary
          h4= result.class.to_s.upcase
          = render partial: result.class.to_s.downcase, locals: {resource: result}
    - else
      h2= "No result"