config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  get :search, to: 'search#result'

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  devise_for :users, controllers: {
      omniauth_callbacks: 'oauth_callbacks',
      confirmations: 'oauth_confirmations'
  }

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  concern :voteable do
    member do
      post :up
      post :down
      post :cancel
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, concerns: %i[voteable commentable] do
    resources :answers, shallow: true, concerns: %i[voteable commentable] do
      member do
        patch :best
      end
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  mount ActionCable.server => '/cable'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user
    if user
      user.admin? ? admin_abilities : user_abilities
    else
      guest_abilities
    end
  end

  def guest_abilities
    can :read, [Question, Answer, Comment]
    can :search, :all
  end

  def admin_abilities
    can :manage, :all
  end

  def user_abilities
    guest_abilities

    can :me, user
    can :read, user

    can :create, [Question, Answer, Comment, Subscription]
    can :update, [Question, Answer], user_id: user.id
    can :destroy, [Question, Answer, Subscription], user_id: user.id

    can :best, Answer, question: { user_id: user.id }

    can [:up, :cancel, :down], [Question, Answer] do |obj|
      !user.author_of? obj
    end

    can :destroy, Link, linlable: { user_id: user.id }

    can :manage, ActiveStorage::Attachment do |attachment|
      user.author_of? attachment.record
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Voteable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  has_many_attached :files
  has_many :links, dependent: :destroy, as: :linkable

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  after_create :email_notification

  scope :by_best, -> { order(best: :desc) }

  def set_best
    best_answer = question.answers.find_by(best: true)

    transaction do
      best_answer&.update!(best: false)
      update!(best: true)
      question.reward&.update!(user: user)
    end
  end

  private

  def email_notification
    NewAnswerNotificationJob.perform_later(self)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user

  validates :provider, :uid, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true, touch: true
  belongs_to :user

  validates :body, :user, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
  GIST_URL = 'gist.github.com'.freeze

  belongs_to :linkable, polymorphic: true

  validates :name, :url, presence: true
  validates :url, format: URI::regexp(%w[http https])

  def gist_link?
    url_split[2] == GIST_URL
  end

  def gist_contents
    gist = client.gist(url_split.last)
    files = {}

    gist.files.each do |k, v|
      files[k] = v[:content]
    end

    files.values
  end

  private

  def client
    Octokit::Client.new(:access_token => Rails.application.credentials.dig(:gist_access_token))
  end

  def url_split
    url.split('/')
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Voteable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy
  has_one :reward, dependent: :destroy
  belongs_to :user

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :calculate_reputation, :subscribe_to_author

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end

  def subscribe_to_author
    subscriptions.create(user: user)
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :question
  belongs_to :user, optional: true

  has_one_attached :image

  validates :title, :image, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_many :answers
  has_many :rewards
  has_many :votes
  has_many :comments
  has_many :authorizations, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable,
         :omniauthable, omniauth_providers: %i[github facebook twitter vkontakte]

  def author_of?(object)
    self.id == object.user_id
  end
  
  def voted?(object)
    object.votes.where(user: self).exists?
  end

  def subscribed_of?(object)
    object.subscriptions.where(user: self).exists?
  end

  def self.find_for_oauth(auth)
    Services::FindForOauth.new(auth).call
  end

  def create_authorization(auth)
    self.authorizations.create(provider: auth.provider, uid: auth.uid)
  end

  protected

  def confirmation_required?
    false
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :voteable, polymorphic: true
  belongs_to :user

  validates :vote, presence: true
  validates :vote, inclusion: [-1, 1]
  validates :user_id, uniqueness: { scope: %i[voteable_type voteable_id] }
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!
  before_action :load_link

  def destroy
    resource = @link.linkable

    if current_user.author_of?(resource)
      @link.destroy
    else
      head :forbidden
    end
  end

  private

  def load_link
    @link = Link.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def collection_cache_key_for(model)
    klass = model.to_s.capitalize.constantize
    count = klass.count
    max_updated_at = klass.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "#{model.to_s.pluralize}/collection-#{count}-#{max_updated_at}"
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p> <!--TODO: to slim-->
    <p class="alert"><%= alert %></p> <!--TODO: to slim-->

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title Qna
    = csrf_meta_tags
    = csp_meta_tag
    = action_cable_meta_tag
    = Gon::Base.render_data

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

  body
    = render 'shared/nav'

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  .alert.alert-danger
    b= "#{resource.errors.count} error(s) detected: "
    ul
      -resource.errors.full_messages.each do |message|
        li= message

app/views/shared/_nav.html.slim
.navbar.navbar-default.navbar-static-top
  .container
    .row
      .col-lg-9
        a.navbar-brand
          = link_to image_tag('qna_logo.png', size: '60x60', alt: 'QnAlogo'), questions_path

        .navbar-right
          p= render 'search/search'

          .small
            - if user_signed_in?
              nav-link.dropdown-toggle data-toggle="dropdown" href="#"
                a= current_user.email
                span.caret
              ul.dropdown-menu
                li
                  a= link_to 'My rewards', rewards_path
                li.divider
                li
                  a= link_to 'Sign out', destroy_user_session_path, method: :delete
            - else
              p= link_to 'Sign in', new_user_session_path

app/views/shared/_votes.html.slim
h6 Rating:
.rating
  p= resource.rating

.rating_button
  - if user_signed_in? && !current_user.author_of?(resource)
    em.small
      .cancel_vote style = "#{'display: none' unless current_user.voted?(resource)}"
        = link_to 'Cancel vote', polymorphic_path(resource, action: :cancel), method: :post, remote: true, data: {type: :json}

      .change_vote style = "#{'display: none' if current_user.voted?(resource)}"
        = link_to 'Up', polymorphic_path(resource, action: :up), method: :post, remote: true, data: {type: :json}
        = ' | '
        = link_to 'Down', polymorphic_path(resource, action: :down), method: :post, remote: true, data: {type: :json}