config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  get :search, to: 'search#result'

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  devise_for :users, controllers: {
      omniauth_callbacks: 'oauth_callbacks',
      confirmations: 'oauth_confirmations'
  }

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  concern :voteable do
    member do
      post :up
      post :down
      post :cancel
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, concerns: %i[voteable commentable] do
    resources :answers, shallow: true, concerns: %i[voteable commentable] do
      member do
        patch :best
      end
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Voteable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  has_many_attached :files
  has_many :links, dependent: :destroy, as: :linkable

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  after_create :email_notification

  scope :by_best, -> { order(best: :desc) }

  def set_best
    best_answer = question.answers.find_by(best: true)

    transaction do
      best_answer&.update!(best: false)
      update!(best: true)
      question.reward&.update!(user: user)
    end
  end

  private

  def email_notification
    NewAnswerNotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!, only: %i[create destroy update best]
  before_action :load_question, only: :create
  before_action :load_answer, only: %i[destroy show update best]
  after_action :publish_answer, only: [:create]

  authorize_resource

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def best
    @question = @answer.question

    @answer.set_best
  end

  def destroy
    @answer.destroy
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url])
  end

  def publish_answer
    return if @answer.errors.any?

    attachments = @answer.files.map do |file|
      { id: file.id,
        filename: file.filename.to_s,
        url: Rails.application.routes.url_helpers.rails_blob_path(file, only_path: true)
      }
    end

    ActionCable.server.broadcast(
        "answers_question_#{@question.id}",
        answer: @answer,
        rating: @answer.rating,
        links: @answer.links,
        attachments: attachments
    )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :question, only: [:create]
  before_action :answer, only: [:show, :update, :destroy]

  authorize_resource

  def show
    render json: answer
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_resource_owner

    if @answer.save
      render json: answer, status: :created
    else
      render json: { errors: answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    if answer.update(answer_params)
      render json: answer, status: :created
    else
      render json: { errors: answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    if answer.destroy
      render json: {}, status: :ok
    else
      render json: { errors: answer.errors }, status: :unprocessable_entity
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def answer
    @answer ||= Answer.find(params[:id])
  end

  def question
    @question ||= Question.find(params[:question_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  - if answer.persisted?
    div class="answer_#{answer.id}"
      p= 'TheBest' if answer.best?
      p= answer.body
      .answer_votes
        = render 'shared/votes', resource: answer
      .answer_links
        = render 'links/links', resource: answer
      .answer_files
        = render 'attachments/attachments', resource: answer
      .answer_comments
        = render 'comments/comments', resource: answer
      .add_comment
        = render 'comments/form', resource: answer

      - if current_user&.author_of?(answer.question)
        em.small= link_to 'Best answer', best_answer_path(answer), method: :patch, remote: true

      - if current_user&.author_of?(answer)
        = ' | '
        em.small= link_to 'Delete answer', answer_path(answer), method: :delete, remote: true, data: { confirm: "Are you sure?" }
        = ' | '
        em.small= link_to 'Edit answer', '#', class: 'edit-answer-link', data: { answer_id: answer.id }

      = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
        p
          = f.label :body
        p
          = f.text_area :body
        p
          = f.fields_for :links do |l|
          = link_to_add_association 'Add link', f, :links, partial: 'links/link_fields'
        p
          = f.label :files
          = f.file_field :files, multiple: true, direct_upload: true

        p= f.submit 'Save'
      hr

app/views/answers/best.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  $('.answers').html('<%= j render @question.answers.by_best %>');
<% end %>

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');  // j экранирует все js
  $('.new_answer #answer_body').val('');
  $('.nested-fields').remove();
<% end %>

app/views/answers/destroy.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  $('.answer_<%= @answer.id %>').remove();
<% end %>

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  $('.answer_<%= @answer.id %>').html('<%= j render @answer %>');
<% end %>